### ISSUE TITLE
Controllers in different Feature Directory

### ISSUE THREAD

**Issue by HansS** [maximilianschmitt/ng-autobootstrap#6]
I would like to have the controller in my feature directory. For example for feature 'People' i have a directory ...\people with people.html, people.css and people-controller.js, people-service.js in it.
How do i have to set the options so that ng-autobootstrap finds the controller, the service or the factory?

**Comment by maximilianschmitt** [comment]
Hey HansS! You will need to override the [default options](https://github.com/maximilianschmitt/ng-autobootstrap#configuring-ng-autobootstrap) to look something like this:

``` js
var options = {
    moduleTypes: {
        controller: {
            path: '**/*-controller.js',
            casing: 'pascalCase',
            omit: '-controller'
        },
        service: {
            path: '**/*-service.js',
            casing: 'camelCase',
            omit: '-service'
        }
    }
};
```

We're omitting `-controller` so that your controller doesn't end up being called `PeopleControllerController` or something like that. The paths are specified as globs so you have a lot of flexibility here. Let me know if it works for you!
